### ISSUE TITLE
Cancel or ignore specific directional swipes

### ISSUE THREAD

**Issue by pureux** [leandrowd/react-easy-swipe#4]
We're using react-easy-swipe to implement a carousel in our app, to much success, but on a mobile phone if the carousel takes up most of the height of the screen, the user can't swipe to get below the carousel (or swipe-able area, to be more generic) because the library eats that swipe event and doesn't propagate.

I'd like to be able to specify certain directions to include or exclude, or have the ability to cancel handling a swipe event based on my own determination, so the browser can handle it and continue moving the page.

You can reproduce the issue by opening your demo page on your phone or using the Chrome Dev Tools to mimic a mobile device.  swipe to scroll the demo area into view and then try to swipe within the demo area to continue further down the page.  It will trap the swipe event (writing it out to the console) but doesn't provide a way to ignore it.

**Comment by leandrowd** [comment]
Hi @pureux, thanks for raising the issue. It was fixed and published. Please get the latest version and let me know if it is ok.

If you return `true` in the handler passed to `onSwipeMove` it will call `preventDefault`. Otherwise, it will scroll.

Check the demo of my carousel plugin working with the new version: http://react-responsive-carousel.js.org/

**Comment by carpben** [comment]
It would be nice to allow easy opt out from swipe if a user wants to scroll, and vice versa. This might be what the OP meant. So far I haven't been able to achieve either. 
One thing I'm trying is : 

```
    onMove=(position)=> 
    if Math.abs(position.y)<15 return true
```

to avoid scroll on a small finger movement while swiping to a side. However this fails and the browser consoles an error: "[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."
